spring:
  datasource:
    url: jdbc:mysql://localhost:3306/security_demo_db
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: create-drop

    show-sql: true

server:
  error:
    include-stacktrace: never